const projectData = {
    1: {
        title: "DevOpsとゲーム開発の融合：Hinataのデジタルプレイグラウンド",
        author: "Hinata Nguyen",
        authorBio: "日本出身のDevOpsエンジニア兼ゲーム開発者です。スケーラブルなシステム構築と没入感のあるデジタル体験の創造に情熱を注いでいます。自動化、クラウドインフラ、クリエイティブなコーディングの交差点で活躍し、技術的に堅牢でありながら芸術的にも魅力的なツールやゲームを開発しています",
        category1: "DevOps Engineering",
        category2: "Game Developer",
        description: "このポートフォリオでは、日本を拠点に活動するDevOpsエンジニア兼ゲーム開発者、Hinataの作品をご紹介しています。クラウド自動化やCI/CDパイプラインから、インディーゲーム開発、インタラクティブデザインに至るまで、幅広いプロジェクトをご覧いただけます。",
        avatar: "/images/project_data/project1/avatar-1.jpeg",
        email: "mailto:hinatannguyen2005@gmail.com",
        portfolio: "https://github.com/hinatanguyen",
        mainImage: "/images/project_data/project1/main.jpeg",
        galleryImage1: "/images/project_data/project1/gal1.jpeg",
        galleryImage2: "/images/project_data/project1/gal2.jpeg",
        fullWidthImage: "/images/project_data/project1/full.jpeg"
    },
    2: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Jane Smith",
        authorBio: "Creative designer specializing in visual identity and brand development. Passionate about creating meaningful connections through design.",
        category1: "Graphic Design",
        category2: "Branding",
        description: "A comprehensive design portfolio showcasing various creative works including branding, illustration, and digital design. This project demonstrates mastery of design principles and creative problem-solving skills.",
        avatar: "/images/project_data/",
        email: "mailto:jane.smith@example.com",
        portfolio: "https://janesmith.design.com",
        mainImage: "https://via.placeholder.com/800x600/888888/555555?text=Main+Image",
        galleryImage1: "https://via.placeholder.com/400x300/888888/555555?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/888888/555555?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/888888/555555?text=Full+Width"
    },
    3: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Alex Johnson",
        authorBio: "UX/UI designer focused on creating intuitive and engaging digital experiences. Strong background in user research and interaction design.",
        category1: "UI/UX Design",
        category2: "Web Design",
        description: "An innovative web experience that combines user interface design with interactive elements. This project focuses on user engagement and modern web technologies.",
        avatar: "/images/project_data/",
        email: "mailto:alex.johnson@example.com",
        portfolio: "https://alexjohnson.ux.com",
        mainImage: "https://via.placeholder.com/800x600/777777/444444?text=Main+Image",
        galleryImage1: "https://via.placeholder.com/400x300/777777/444444?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/777777/444444?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/777777/444444?text=Full+Width"
    },
    4: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Sarah Chen",
        authorBio: "Motion designer creating engaging animations and visual effects for digital media and advertising campaigns.",
        category1: "Motion Design",
        category2: "Animation",
        description: "A collection of motion design work including 2D animations, motion graphics, and visual effects for various digital platforms.",
        avatar: "/images/project_data/",
        email: "mailto:sarah.chen@example.com",
        portfolio: "https://sarahchen.motion.com",
        mainImage: "https://via.placeholder.com/800x600/666666/333333?text=Motion+Design",
        galleryImage1: "https://via.placeholder.com/400x300/666666/333333?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/666666/333333?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/666666/333333?text=Full+Width"
    },
    5: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Mark Thompson",
        authorBio: "Architectural visualization specialist focused on creating photorealistic renderings and 3D presentations.",
        category1: "Architecture",
        category2: "3D Visualization",
        description: "Professional architectural visualization work including interior and exterior renderings, virtual tours, and presentation materials.",
        avatar: "/images/project_data/",
        email: "mailto:mark.thompson@example.com",
        portfolio: "https://markthompson.arch.com",
        mainImage: "https://via.placeholder.com/800x600/555555/222222?text=Architecture",
        galleryImage1: "https://via.placeholder.com/400x300/555555/222222?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/555555/222222?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/555555/222222?text=Full+Width"
    },
    6: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Emma Wilson",
        authorBio: "Product designer with expertise in user-centered design and innovative product development.",
        category1: "Product Design",
        category2: "Innovation",
        description: "Innovative product design solutions focusing on user experience, functionality, and aesthetic appeal.",
        avatar: "/images/project_data/",
        email: "mailto:emma.wilson@example.com",
        portfolio: "https://emmawilson.product.com",
        mainImage: "https://via.placeholder.com/800x600/444444/111111?text=Product+Design",
        galleryImage1: "https://via.placeholder.com/400x300/444444/111111?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/444444/111111?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/444444/111111?text=Full+Width"
    },
    7: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "David Lee",
        authorBio: "Professional photographer specializing in portrait, landscape, and commercial photography.",
        category1: "Photography",
        category2: "Visual Arts",
        description: "A diverse portfolio of photography work spanning portrait sessions, landscape photography, and commercial projects.",
        avatar: "/images/project_data/",
        email: "mailto:david.lee@example.com",
        portfolio: "https://davidlee.photo.com",
        mainImage: "https://via.placeholder.com/800x600/999999/666666?text=Photography",
        galleryImage1: "https://via.placeholder.com/400x300/999999/666666?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/999999/666666?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/999999/666666?text=Full+Width"
    },
    8: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Lisa Garcia",
        authorBio: "Digital marketing strategist creating compelling campaigns and brand experiences across digital platforms.",
        category1: "Digital Marketing",
        category2: "Campaign Design",
        description: "Strategic digital marketing campaigns combining creative design with data-driven insights for maximum impact.",
        avatar: "/images/project_data/",
        email: "mailto:lisa.garcia@example.com",
        portfolio: "https://lisagarcia.marketing.com",
        mainImage: "https://via.placeholder.com/800x600/888888/555555?text=Marketing",
        galleryImage1: "https://via.placeholder.com/400x300/888888/555555?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/888888/555555?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/888888/555555?text=Full+Width"
    },
    9: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Ryan Park",
        authorBio: "Concept artist and illustrator creating imaginative worlds and characters for games, films, and publications.",
        category1: "Illustration",
        category2: "Concept Art",
        description: "Original illustrations and concept art showcasing creative storytelling through visual design and character development.",
        avatar: "/images/project_data/",
        email: "mailto:ryan.park@example.com",
        portfolio: "https://ryanpark.art.com",
        mainImage: "https://via.placeholder.com/800x600/777777/444444?text=Illustration",
        galleryImage1: "https://via.placeholder.com/400x300/777777/444444?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/777777/444444?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/777777/444444?text=Full+Width"
    },
    10: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Maya Patel",
        authorBio: "Interactive media designer creating engaging digital experiences through innovative technology and design.",
        category1: "Interactive Design",
        category2: "Digital Media",
        description: "Cutting-edge interactive media projects combining technology, design, and user engagement for immersive experiences.",
        avatar: "/images/project_data/",
        email: "mailto:maya.patel@example.com",
        portfolio: "https://mayapatel.interactive.com",
        mainImage: "https://via.placeholder.com/800x600/666666/333333?text=Interactive+Media",
        galleryImage1: "https://via.placeholder.com/400x300/666666/333333?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/666666/333333?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/666666/333333?text=Full+Width"
    },
    11: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Sophie Martin",
        authorBio: "Fashion designer creating contemporary clothing collections with a focus on sustainable and innovative materials.",
        category1: "Fashion Design",
        category2: "Sustainability",
        description: "Modern fashion collection showcasing sustainable design practices and innovative approaches to contemporary clothing.",
        avatar: "/images/project_data/",
        email: "mailto:sophie.martin@example.com",
        portfolio: "https://sophiemartin.fashion.com",
        mainImage: "https://via.placeholder.com/800x600/555555/222222?text=Fashion+Design",
        galleryImage1: "https://via.placeholder.com/400x300/555555/222222?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/555555/222222?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/555555/222222?text=Full+Width"
    },
    12: {
        title: "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        author: "Alex Rivera",
        authorBio: "Sound designer and audio engineer creating immersive soundscapes for films, games, and interactive media.",
        category1: "Sound Design",
        category2: "Audio Engineering",
        description: "Professional sound design work including music composition, audio effects, and soundscapes for various media projects.",
        avatar: "/images/project_data/",
        email: "mailto:alex.rivera@example.com",
        portfolio: "https://alexrivera.sound.com",
        mainImage: "https://via.placeholder.com/800x600/444444/111111?text=Sound+Design",
        galleryImage1: "https://via.placeholder.com/400x300/444444/111111?text=Gallery+1",
        galleryImage2: "https://via.placeholder.com/400x300/444444/111111?text=Gallery+2",
        fullWidthImage: "https://via.placeholder.com/1200x400/444444/111111?text=Full+Width"
    }
};
